"""Static seed / reference data loaded by ca_firm.setup.install on install and migrate."""

DESIGNATIONS = [   {'can_review': 1, 'can_sign_reports': 1, 'designation_level': 1, 'designation_name': 'Partner'},
    {'can_review': 1, 'can_sign_reports': 1, 'designation_level': 1, 'designation_name': 'EQCR Partner'},
    {'can_review': 1, 'can_sign_reports': 0, 'designation_level': 2, 'designation_name': 'Manager'},
    {'can_review': 1, 'can_sign_reports': 0, 'designation_level': 3, 'designation_name': 'Job Incharge'},
    {'can_review': 1, 'can_sign_reports': 0, 'designation_level': 4, 'designation_name': 'Supervisor'},
    {'can_review': 0, 'can_sign_reports': 0, 'designation_level': 5, 'designation_name': 'Senior'},
    {'can_review': 0, 'can_sign_reports': 0, 'designation_level': 6, 'designation_name': 'Semi Senior'},
    {'can_review': 0, 'can_sign_reports': 0, 'designation_level': 7, 'designation_name': 'Article Assistant'},
    {'can_review': 0, 'can_sign_reports': 0, 'designation_level': 7, 'designation_name': 'Paid Assistant'}]

AUDIT_STANDARDS = [   ('ISA 200', 'Overall Objectives of the Independent Auditor', 'Standard on Auditing'),
    ('ISA 210', 'Agreeing the Terms of Audit Engagements', 'Standard on Auditing'),
    ('ISA 220 (Revised)', 'Quality Management for an Audit of Financial Statements', 'Standard on Auditing'),
    ('ISA 230', 'Audit Documentation', 'Standard on Auditing'),
    ('ISA 240', "The Auditor's Responsibilities Relating to Fraud", 'Standard on Auditing'),
    ('ISA 250', 'Consideration of Laws and Regulations', 'Standard on Auditing'),
    ('ISA 260', 'Communication with Those Charged with Governance', 'Standard on Auditing'),
    ('ISA 265', 'Communicating Deficiencies in Internal Control', 'Standard on Auditing'),
    ('ISA 300', 'Planning an Audit of Financial Statements', 'Standard on Auditing'),
    (   'ISA 315 (Revised)',
        'Identifying and Assessing the Risks of Material Misstatement',
        'Standard on Auditing'),
    ('ISA 320', 'Materiality in Planning and Performing an Audit', 'Standard on Auditing'),
    ('ISA 330', "The Auditor's Responses to Assessed Risks", 'Standard on Auditing'),
    (   'ISA 402',
        'Audit Considerations Relating to an Entity Using a Service Organization',
        'Standard on Auditing'),
    ('ISA 450', 'Evaluation of Misstatements Identified during the Audit', 'Standard on Auditing'),
    ('ISA 500', 'Audit Evidence', 'Standard on Auditing'),
    ('ISA 501', 'Audit Evidence - Specific Considerations for Selected Items', 'Standard on Auditing'),
    ('ISA 505', 'External Confirmations', 'Standard on Auditing'),
    ('ISA 510', 'Initial Audit Engagements - Opening Balances', 'Standard on Auditing'),
    ('ISA 520', 'Analytical Procedures', 'Standard on Auditing'),
    ('ISA 530', 'Audit Sampling', 'Standard on Auditing'),
    ('ISA 540 (Revised)', 'Auditing Accounting Estimates', 'Standard on Auditing'),
    ('ISA 550', 'Related Parties', 'Standard on Auditing'),
    ('ISA 560', 'Subsequent Events', 'Standard on Auditing'),
    ('ISA 570 (Revised)', 'Going Concern', 'Standard on Auditing'),
    ('ISA 580', 'Written Representations', 'Standard on Auditing'),
    ('ISA 600 (Revised)', 'Special Considerations - Group Audits', 'Standard on Auditing'),
    ('ISA 610 (Revised)', 'Using the Work of Internal Auditors', 'Standard on Auditing'),
    ('ISA 620', "Using the Work of an Auditor's Expert", 'Standard on Auditing'),
    ('ISA 700 (Revised)', 'Forming an Opinion and Reporting on Financial Statements', 'Standard on Auditing'),
    ('ISA 701', 'Communicating Key Audit Matters', 'Standard on Auditing'),
    ('ISA 705 (Revised)', 'Modifications to the Opinion', 'Standard on Auditing'),
    ('ISA 706 (Revised)', 'Emphasis of Matter and Other Matter Paragraphs', 'Standard on Auditing'),
    ('ISA 710', 'Comparative Information', 'Standard on Auditing'),
    (   'ISA 720 (Revised)',
        "The Auditor's Responsibilities Relating to Other Information",
        'Standard on Auditing'),
    (   'ISQM 1',
        'Quality Management for Firms that Perform Audits or Reviews of Financial Statements',
        'Standard on Quality Control'),
    ('ISQM 2', 'Engagement Quality Reviews', 'Standard on Quality Control'),
    (   'ISRE 2400 (Revised)',
        'Engagements to Review Historical Financial Statements',
        'Standard on Review Engagements')]

FS_AREAS = [   ('Revenue', 'Profit and Loss', 'High'),
    ('Purchases and Expenses', 'Profit and Loss', 'Medium'),
    ('Property, Plant and Equipment', 'Balance Sheet', 'Medium'),
    ('Intangible Assets', 'Balance Sheet', 'Medium'),
    ('Inventory', 'Balance Sheet', 'High'),
    ('Cash and Bank Balances', 'Balance Sheet', 'Medium'),
    ('Trade Receivables', 'Balance Sheet', 'High'),
    ('Trade Payables', 'Balance Sheet', 'Medium'),
    ('Loans and Borrowings', 'Balance Sheet', 'Medium'),
    ('Provisions and Contingent Liabilities', 'Balance Sheet', 'High'),
    ('Employee Benefits and Payroll', 'Both', 'Medium'),
    ('Related Party Transactions', 'Both', 'High'),
    ('Equity and Reserves', 'Balance Sheet', 'Low'),
    ('Investments', 'Balance Sheet', 'Medium'),
    ('Taxation - Current and Deferred', 'Both', 'High'),
    ('Other Income and Other Expenses', 'Profit and Loss', 'Low')]

ASSERTIONS = [   ('Existence', 'Account Balances'),
    ('Completeness', 'Account Balances'),
    ('Rights and Obligations', 'Account Balances'),
    ('Accuracy, Valuation and Allocation', 'Account Balances'),
    ('Occurrence', 'Classes of Transactions and Events'),
    ('Cut-off', 'Classes of Transactions and Events'),
    ('Classification', 'Classes of Transactions and Events'),
    ('Presentation', 'Presentation and Disclosure')]

RISK_CATEGORIES = [   ('Management Override of Controls', 'Fraud'),
    ('Revenue Recognition', 'Fraud'),
    ('Complex or Unusual Transactions', 'Inherent'),
    ('Significant Accounting Estimates', 'Inherent'),
    ('IT General Controls Weakness', 'Control'),
    ('Related Party Transactions', 'Inherent'),
    ('Going Concern', 'Business'),
    ('Regulatory Non-Compliance', 'Business')]

APPLICABLE_LAWS = [   'Companies Act, 2017',
    'Income Tax Ordinance, 2001',
    'Sales Tax Act, 1990',
    'Federal Excise Act, 2005',
    'Foreign Exchange Regulation Act, 1947 (SBP Regulations)',
    'Anti-Money Laundering Act, 2010',
    'SECP Code of Corporate Governance Regulations, 2019',
    'SECP Companies (Accounting and Auditing Standards) Rules, 2015',
    'International Financial Reporting Standards (IFRS) as adopted in Pakistan',
    "Fourth Schedule to the Companies Act, 2017 (Auditor's Report)",
    'Fifth Schedule to the Companies Act, 2017 (Financial Statement Disclosures)']

PROCEDURE_TYPES = [   'Inquiry',
    'Observation',
    'Inspection of Records or Documents',
    'Inspection of Tangible Assets',
    'Recalculation',
    'Reperformance',
    'External Confirmation',
    'Analytical Procedure',
    'Test of Control',
    'Computer Assisted Audit Technique (CAAT)']

CAAT_TEMPLATES = [   ('Duplicate Invoice / Payment Detection', 'Duplicate Detection', 'Trade Payables'),
    ('Invoice Sequence Gap Test', 'Sequence Gap Test', 'Revenue'),
    ("Benford's Law Analysis on GL Entries", "Benford's Law", None),
    ('Round Sum Journal Entry Test', 'Round Sum Test', None),
    ('Three-Way Match - PO, GRN, Invoice', 'Three-Way Match', 'Purchases and Expenses'),
    ('Journal Entries Posted by Unauthorized Users', 'Journal Entry Testing', None),
    ('Journal Entries Posted on Weekends/Holidays', 'Journal Entry Testing', None),
    ('Outlier Detection on Expense Accounts', 'Outlier Detection', 'Purchases and Expenses'),
    ('Segregation of Duties Conflict Report', 'Segregation of Duties', None)]

CHECKLIST_TEMPLATES = [   {   'category': 'Engagement Acceptance',
        'items': [   'Integrity of promoters / management assessed',
                     "Firm's competence and resources to perform the engagement confirmed",
                     'Independence and conflict of interest check completed for all team members',
                     'Compliance with ICAI Code of Ethics confirmed',
                     'Communication with previous auditor completed (if applicable)',
                     'Engagement letter drafted and approved by Engagement Partner',
                     'Client acceptance / continuance evaluation approved'],
        'template_name': 'Engagement Acceptance Checklist'},
    {   'category': 'PBC - Documents Required',
        'items': [   'Trial Balance and Financial Statements (Draft)',
                     'Statutory Registers and Minutes of Board / General Meetings',
                     'Bank Statements and Bank Reconciliation Statements',
                     'Fixed Asset Register',
                     'Inventory Records and Stock Valuation Statement',
                     'Debtors and Creditors Ageing',
                     'Loan Agreements and Confirmations',
                     'Sales Tax Returns and Reconciliations (Monthly Sales Tax Returns)',
                     'Withholding Tax Statements and Challans',
                     'Related Party Transaction Details',
                     'Details of Contingent Liabilities and Commitments',
                     'Copies of Board Resolutions for Key Transactions'],
        'template_name': 'PBC - Standard Documents Required'},
    {   'category': 'Engagement Completion',
        'items': [   'All audit programs completed and signed off',
                     'All review notes cleared',
                     'Materiality and performance materiality finalized and adhered to',
                     'Summary of uncorrected misstatements evaluated',
                     'Subsequent events review completed',
                     'Written representation letter obtained',
                     'Going concern assessment completed',
                     'Key audit matters identified and documented',
                     'EQCR completed (if applicable)',
                     'Financial statements agreed to underlying working papers',
                     'Management letter drafted',
                     'Report reference / engagement archive number recorded'],
        'template_name': 'Engagement Completion Checklist'},
    {   'category': 'Statutory Compliance',
        'items': [   'Proper books of account as required by law have been kept by the company',
                     'Statement of financial position, profit and loss account and cash flow statement agree '
                     'with the books of account',
                     "Expenditure incurred was for the purpose of the company's business",
                     'Zakat deductible was deducted and deposited in the Central Zakat Fund (if applicable)',
                     'Investments made and expenditure incurred during the year were in accordance with the '
                     'objects of the company',
                     'Compliance with the Fourth Schedule to the Companies Act, 2017 (form and content of '
                     'accounts)',
                     'Compliance with applicable IFRS / accounting standards as notified by SECP',
                     "Related party transactions reviewed for approval and arm's length pricing (Section "
                     '208)',
                     'Compliance with SECP Code of Corporate Governance Regulations, 2019 (if a listed '
                     'company)',
                     'Adequacy of the internal control system over financial reporting evaluated',
                     'Going concern basis of preparation assessed',
                     'Compliance with Anti-Money Laundering Act, 2010 customer due diligence requirements '
                     '(if applicable)',
                     'Matters to be reported under Section 250 (if any) identified and documented'],
        'template_name': "Companies Act 2017 - Statutory Auditor's Report Checklist"},
    {   'category': 'Client Onboarding',
        'items': [   'Client master data created with statutory details',
                     'KYC documents collected (NTN, Sales Tax registration, SECP incorporation certificate)',
                     'Engagement letter signed',
                     'Client acceptance and continuance evaluation completed',
                     'Independence declarations obtained from all team members',
                     'Client contacts and portal access set up',
                     'Fee structure agreed and documented'],
        'template_name': 'Client Onboarding Checklist'}]

AUDIT_PROGRAM_TEMPLATES = [   {   'fs_area': 'Revenue',
        'steps': [   (   'Obtain and review revenue recognition policy for compliance with IFRS 15',
                         'Presentation',
                         'Inspection of Records or Documents',
                         0),
                     (   'Perform analytical procedures on revenue by month / product / segment vs prior '
                         'year',
                         'Completeness',
                         'Analytical Procedure',
                         0),
                     (   'Select sample of sales invoices and vouch to dispatch documents and customer '
                         'acknowledgement',
                         'Occurrence',
                         'Inspection of Records or Documents',
                         0),
                     (   'Test cut-off by examining sales around year-end',
                         'Cut-off',
                         'Inspection of Records or Documents',
                         0),
                     (   'Run duplicate invoice / sequence gap CAAT on sales register',
                         'Completeness',
                         'Computer Assisted Audit Technique (CAAT)',
                         1),
                     (   'Circularize external confirmations to major debtors',
                         'Existence',
                         'External Confirmation',
                         0),
                     (   'Review credit notes issued after year-end for revenue reversal risk',
                         'Occurrence',
                         'Inspection of Records or Documents',
                         0)],
        'template_name': 'Revenue - Standard Audit Program'},
    {   'fs_area': 'Trade Receivables',
        'steps': [   (   'Obtain debtors ageing and agree total to trial balance / general ledger',
                         'Completeness',
                         'Reperformance',
                         0),
                     (   'Select sample of debtors for external confirmation (positive confirmation)',
                         'Existence',
                         'External Confirmation',
                         0),
                     (   'Review subsequent receipts for balances not confirmed',
                         'Existence',
                         'Inspection of Records or Documents',
                         0),
                     (   'Assess adequacy of provision for doubtful debts / expected credit loss',
                         'Accuracy, Valuation and Allocation',
                         'Recalculation',
                         0),
                     (   'Review related party receivables for disclosure completeness',
                         'Presentation',
                         'Inspection of Records or Documents',
                         0)],
        'template_name': 'Trade Receivables - Standard Audit Program'},
    {   'fs_area': 'Trade Payables',
        'steps': [   (   'Obtain creditors ageing and agree to trial balance',
                         'Completeness',
                         'Reperformance',
                         0),
                     (   'Perform search for unrecorded liabilities - review post year-end payments and '
                         'invoices',
                         'Completeness',
                         'Inspection of Records or Documents',
                         0),
                     (   'Select sample of payables for external confirmation',
                         'Existence',
                         'External Confirmation',
                         0),
                     (   'Run three-way match CAAT (PO-GRN-Invoice) for major vendors',
                         'Occurrence',
                         'Computer Assisted Audit Technique (CAAT)',
                         1)],
        'template_name': 'Trade Payables - Standard Audit Program'},
    {   'fs_area': 'Property, Plant and Equipment',
        'steps': [   (   'Obtain fixed asset register and agree opening balances to prior year working '
                         'papers',
                         'Existence',
                         'Inspection of Records or Documents',
                         0),
                     (   'Vouch additions during the year to invoices and capitalization approvals',
                         'Occurrence',
                         'Inspection of Records or Documents',
                         0),
                     (   'Vouch disposals and verify gain/loss on disposal computation',
                         'Rights and Obligations',
                         'Recalculation',
                         0),
                     (   'Recalculate depreciation for a sample of assets as per approved useful life / '
                         'rates',
                         'Accuracy, Valuation and Allocation',
                         'Recalculation',
                         0),
                     (   'Perform / observe physical verification of fixed assets',
                         'Existence',
                         'Inspection of Tangible Assets',
                         0),
                     (   'Verify title deeds of immovable property held in the name of the company',
                         'Rights and Obligations',
                         'Inspection of Records or Documents',
                         0)],
        'template_name': 'Property, Plant and Equipment - Standard Audit Program'},
    {   'fs_area': 'Inventory',
        'steps': [   ('Attend / observe physical inventory count at year end', 'Existence', 'Observation', 0),
                     (   'Test stock valuation - lower of cost and net realizable value',
                         'Accuracy, Valuation and Allocation',
                         'Recalculation',
                         0),
                     (   'Review provision for slow moving / obsolete inventory',
                         'Accuracy, Valuation and Allocation',
                         'Analytical Procedure',
                         0),
                     (   'Test cut-off of goods received and dispatched around year-end',
                         'Cut-off',
                         'Inspection of Records or Documents',
                         0),
                     (   'Reconcile physical count results with perpetual inventory records',
                         'Completeness',
                         'Reperformance',
                         0)],
        'template_name': 'Inventory - Standard Audit Program'},
    {   'fs_area': 'Cash and Bank Balances',
        'steps': [   (   'Obtain bank confirmations for all accounts held during the year',
                         'Existence',
                         'External Confirmation',
                         0),
                     (   'Review bank reconciliation statements and test reconciling items',
                         'Completeness',
                         'Reperformance',
                         0),
                     (   'Perform / observe cash count for material cash balances',
                         'Existence',
                         'Observation',
                         0),
                     (   'Review for restrictions on bank balances (e.g. margin money, escrow)',
                         'Presentation',
                         'Inspection of Records or Documents',
                         0)],
        'template_name': 'Cash and Bank - Standard Audit Program'},
    {   'fs_area': 'Provisions and Contingent Liabilities',
        'steps': [   (   "Obtain management's assessment of contingent liabilities and litigation status",
                         'Completeness',
                         'Inquiry',
                         0),
                     (   'Obtain legal confirmation letters from external legal counsel',
                         'Completeness',
                         'External Confirmation',
                         0),
                     (   'Evaluate reasonableness of provisions recognized against IAS 37 recognition '
                         'criteria',
                         'Accuracy, Valuation and Allocation',
                         'Analytical Procedure',
                         0),
                     (   'Review board minutes and correspondence for undisclosed claims',
                         'Completeness',
                         'Inspection of Records or Documents',
                         0)],
        'template_name': 'Provisions and Contingent Liabilities - Standard Audit Program'},
    {   'fs_area': 'Taxation - Current and Deferred',
        'steps': [   (   'Recompute current tax provision as per Income Tax Ordinance, 2001',
                         'Accuracy, Valuation and Allocation',
                         'Recalculation',
                         0),
                     (   'Verify deferred tax computation and reconciliation of temporary differences',
                         'Accuracy, Valuation and Allocation',
                         'Recalculation',
                         0),
                     (   'Reconcile monthly sales tax returns with books of account',
                         'Completeness',
                         'Reperformance',
                         0),
                     (   'Review withholding tax compliance and reconciliation with challans deposited',
                         'Completeness',
                         'Reperformance',
                         0)],
        'template_name': 'Taxation - Standard Audit Program'}]
